### ISSUE TITLE
词库里面没有的词语，比较结果是0

### ISSUE THREAD

**Issue by soulspirit1229** [BiLiangLtd/WordSimilarity#4]

**Comment by yaleimeng** [comment]
这是**默认设定**（或许本来也没有哪两个词对比会是0，最小也是0.000000*****）。
当然追求完美的你也可以改为负数，表示这其实是一个异常。
我的项目[Final_word_Similarity ](https://github.com/yaleimeng/Final_word_Similarity) 您也可以了解一下。

**Comment by zhaochongzc** [comment]
我将整个文件解压到python目录下
:\Users\15311\AppData\Local\Programs\Python\Python36\python.exe C:/Users/15311/Desktop/adsfs/test/test_word_similarity.py
Traceback (most recent call last):
  File "C:/Users/15311/Desktop/adsfs/test/test_word_similarity.py", line 38, in <module>
    a.test_similarity_2010()
  File "C:/Users/15311/Desktop/adsfs/test/test_word_similarity.py", line 12, in test_similarity_2010
    ws_tool = WordSimilarity2010()
  File "C:\Users\15311\AppData\Roaming\Python\Python36\site-packages\word_similarity\__init__.py", line 101, in __init__
    super(WordSimilarity2010, self).__init__()
  File "C:\Users\15311\AppData\Roaming\Python\Python36\site-packages\word_similarity\__init__.py", line 20, in __init__
    self._load_cilin(t_cilin_path)
  File "C:\Users\15311\AppData\Roaming\Python\Python36\site-packages\word_similarity\__init__.py", line 45, in _load_cilin
    line = file_obj.readline()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xba in position 11: illegal multibyte sequence

却报错，大神这是为什么呢
能出一份详细一点的使用教程吗

**Comment by yaleimeng** [comment]
这个项目算法已是8年前的了。我的项目[Final_word_Similarity](https://github.com/yaleimeng/Final_word_Similarity) 按最近2年的新算法迭代了几次，计算效果遥遥领先，不了解一下吗？ @zhaochongzc  @soulspirit1229

**Comment by zhaochongzc** [comment]
那肯定要拜读一下啦，谢谢你啦
