### ISSUE TITLE
windows下使用有编码问题

### ISSUE THREAD

**Issue by yiqiyu** [BiLiangLtd/WordSimilarity#7]
`Traceback (most recent call last):
  File "D:/projects/miscellaneous/test.py", line 5, in <module>
    ws_tool = WordSimilarity2010()
  File "C:\Users\00015426\AppData\Local\Programs\Python\Python37\lib\site-packages\word_similarity\__init__.py", line 101, in __init__
    super(WordSimilarity2010, self).__init__()
  File "C:\Users\00015426\AppData\Local\Programs\Python\Python37\lib\site-packages\word_similarity\__init__.py", line 20, in __init__
    self._load_cilin(t_cilin_path)
  File "C:\Users\00015426\AppData\Local\Programs\Python\Python37\lib\site-packages\word_similarity\__init__.py", line 45, in _load_cilin
    line = file_obj.readline()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xba in position 11: illegal multibyte sequence`

希望作者可以增加编码兼容，比如说`file_obj = open(file_path, 'r', encoding="utf-8")`

**Comment by JackiyWu** [comment]
同有问题

**Comment by cccccrj** [comment]
同

**Comment by lagrahhn** [comment]
在源码的第41行，
改为file_obj = open(file_path, 'r',encoding='utf-8')
